"use client";

import * as React from "react";
import Link from "next/link";
import { AlertCircle, ArrowRight, Loader2, Sparkles } from "lucide-react";
import { Badge, Button } from "@/components/admin/ui";
import { isActionError } from "@/lib/action-result";
import { triageInboxAction } from "@/app/admin/(dashboard)/messages/actions";
import type { InboxDigest } from "@/lib/ai/inbox";

/**
 * AI Inbox Assistant panel.
 *
 * Collapsed until asked. The digest costs a provider call, so it is never
 * generated by simply loading the page — the operator presses the button, and
 * the result lives in page state only.
 *
 * Every item links to the message it came from. That is the difference between
 * a digest and a summary: the operator should be one click from the evidence,
 * because the assistant's judgement is a suggestion, not a verdict.
 */

type State =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "ready"; digest: InboxDigest }
  | { kind: "note"; note: string }
  | { kind: "error"; message: string };

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
}

function formatDate(iso: string | null): string {
  return iso ? new Date(iso).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "—";
}

export function InboxAssistantPanel() {
  const [state, setState] = React.useState<State>({ kind: "idle" });
  const running = state.kind === "loading";
  /**
   * Synchronous twin of `running`. State is stale inside a handler, and this
   * call costs tokens — the same defect the copilot's send guard had, so it is
   * guarded the same way rather than relying on the disabled attribute alone.
   */
  const inFlight = React.useRef(false);

  async function run() {
    if (inFlight.current) return;
    inFlight.current = true;
    setState({ kind: "loading" });

    try {
      const result = await triageInboxAction();

      if (isActionError(result)) {
        setState({ kind: "error", message: result.formError ?? "Could not review the inbox." });
        return;
      }
      if (result.data.digest) {
        setState({ kind: "ready", digest: result.data.digest });
        return;
      }
      setState({ kind: "note", note: result.data.note ?? "Nothing to review." });
    } catch (error) {
      console.error("[inbox assistant] request failed:", error);
      setState({ kind: "error", message: "Could not reach the assistant. Please try again." });
    } finally {
      inFlight.current = false;
    }
  }

  return (
    <section
      aria-labelledby="inbox-assistant-heading"
      className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-5"
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h2
            id="inbox-assistant-heading"
            className="flex items-center gap-2 text-sm font-semibold text-white"
          >
            <Sparkles className="size-4 text-slate-500" aria-hidden />
            Needs your attention
          </h2>
          <p className="mt-0.5 text-xs text-slate-500">
            Reviews recent inbound mail and picks out what is actually waiting on you.
          </p>
        </div>

        <Button size="sm" variant="secondary" onClick={run} disabled={running} isLoading={running}>
          {state.kind === "idle" ? "Review inbox" : "Refresh"}
        </Button>
      </div>

      <div aria-live="polite" className="mt-4">
        {state.kind === "idle" && (
          <p className="text-xs text-slate-600">
            Nothing is analysed until you ask — this runs one AI pass over the last two weeks of
            inbound mail.
          </p>
        )}

        {state.kind === "loading" && (
          <p className="flex items-center gap-2 text-sm text-slate-500">
            <Loader2 className="size-4 animate-spin" aria-hidden />
            Reading your inbox…
          </p>
        )}

        {state.kind === "note" && <p className="text-sm text-slate-400">{state.note}</p>}

        {state.kind === "error" && (
          <p className="flex items-start gap-2 rounded-md border border-red-500/20 bg-red-500/5 px-3 py-2 text-sm text-red-400">
            <AlertCircle className="mt-0.5 size-4 shrink-0" aria-hidden />
            {state.message}
          </p>
        )}

        {state.kind === "ready" && <Digest digest={state.digest} />}
      </div>
    </section>
  );
}

function Digest({ digest }: { digest: InboxDigest }) {
  if (digest.items.length === 0) {
    return (
      <div className="space-y-1">
        <p className="text-sm text-slate-300">Nothing needs you right now.</p>
        <p className="text-xs text-slate-600">
          Reviewed {digest.consideredCount} message{digest.consideredCount === 1 ? "" : "s"} ·{" "}
          {formatTime(digest.generatedAt)}
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <ul className="space-y-2">
        {digest.items.map((item) => (
          <li key={item.messageId}>
            <Link
              href={`/admin/messages/${item.messageId}`}
              className="group flex gap-3 rounded-md border border-white/[0.06] px-3 py-2.5 transition-colors hover:bg-white/[0.04]"
            >
              <span className="mt-0.5 shrink-0">
                <Badge variant={item.priority === "high" ? "danger" : "neutral"}>
                  {item.priority === "high" ? "Now" : "Soon"}
                </Badge>
              </span>

              <span className="min-w-0 flex-1">
                <span className="flex items-baseline gap-2">
                  <span className="truncate text-sm font-medium text-slate-200">{item.headline}</span>
                  <span className="shrink-0 text-xs text-slate-600">{formatDate(item.receivedAt)}</span>
                </span>
                <span className="mt-0.5 block truncate text-xs text-slate-500">
                  {item.from ?? "unknown sender"}
                </span>
                <span className="mt-1 block text-xs text-slate-400">{item.why}</span>
                <span className="mt-1 flex items-center gap-1 text-xs text-slate-300">
                  <ArrowRight className="size-3 shrink-0 text-slate-600" aria-hidden />
                  {item.nextStep}
                </span>
              </span>
            </Link>
          </li>
        ))}
      </ul>

      <p className="text-xs text-slate-600">
        {digest.items.length} of {digest.consideredCount} reviewed
        {digest.noActionCount > 0 && ` · ${digest.noActionCount} need nothing`} ·{" "}
        {formatTime(digest.generatedAt)} · check anything important yourself
      </p>
    </div>
  );
}
